name: borrowed_stuff
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_slidable: ^0.5.4
  image_picker: ^0.6.3+4
  flushbar: ^1.9.1
  url_launcher: ^5.4.11

  # Data e internacionalização
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.0
  # brasil_fields: ^0.3.0 teria de testar com outra versão talvez pois com essa aí quando usei a de telefone a digitação não funcionava corretamente
  mask_text_input_formatter: ^1.0.7 # Achei essa implementação usando máscara que funcionou melhor
  flutter_localizations:
    sdk: flutter


  # Banco de dados (produção)
  path_provider: ^1.6.5
  sembast: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true